add_lib(
        stream
        stream.cpp
        data_stream_source/data_stream_source.cpp
        data_stream_source/file_stream_source.cpp
        data_stream_source/simple_stream_source.cpp
        data_stream_source/sift_stream_source.cpp
        data_stream_source/streaming_source.cpp
)
target_link_libraries(
        stream
        PRIVATE
        function
        common
)

add_library(
        stream_runtime
        OBJECT
        stream_environment.cpp
)
target_link_libraries(
        stream_runtime
        PUBLIC
        stream
        query
        function
        common
        concurrency
        execution
        storage
        utils
        externalRuntimeLibs
)